/**
 * `pnpm registry:gen` (docs/contracts/module-manifest.md rule 1). Next.js can't discover modules
 * at runtime, so this finds every src/modules/<id>/manifest.ts, validates the manifests together
 * with the core manifest, and writes src/platform/registry/generated.ts, which imports each one
 * statically, sorted by module id. The file is committed; `pnpm registry:gen --check` (CI) fails
 * when it's stale. The pre-scripts run it before dev, build, typecheck and test.
 *
 * Run with the `react-server` condition (see package.json), so manifests may import server-only
 * code. Icons are checked against lucide-react's icon index file, read as text, because
 * lucide-react itself can't load under that condition.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { glob } from "node:fs/promises";
import { createRequire } from "node:module";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { format, resolveConfig } from "prettier";

import type { ModuleManifest } from "@/contracts/module-manifest";

import { coreManifest } from "./core-manifest";
import { validateManifests } from "./validate";

export const GENERATED_FILE = "src/platform/registry/generated.ts";
const MODULE_ID = /^[a-z][a-z0-9-]{1,63}$/;

/** Module folders that have a manifest, sorted by id. */
export async function discoverModuleIds(root: string): Promise<string[]> {
  const ids: string[] = [];
  for await (const file of glob("src/modules/*/manifest.ts", { cwd: root })) {
    const id = file.split(/[\\/]/)[2];
    if (id !== undefined) ids.push(id);
  }
  return ids.sort();
}

/** "sales-crm" → "salesCrmManifest". */
function identifierFor(id: string): string {
  return `${id.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase())}Manifest`;
}

/** The generated.ts source for these module ids (before formatting). */
export function renderGenerated(ids: readonly string[]): string {
  const imports = ids
    .map((id) => `import ${identifierFor(id)} from "@/modules/${id}/manifest";`)
    .join("\n");
  return [
    "// Generated by `pnpm registry:gen` (src/platform/registry/codegen.ts). Don't edit it by hand.",
    "// Every module manifest, imported statically and sorted by module id. Committed; CI fails",
    "// when it's stale.",
    "",
    'import type { ModuleManifest } from "@/contracts/module-manifest";',
    ...(imports === "" ? [] : ["", imports]),
    "",
    `export const moduleManifests: readonly ModuleManifest[] = [${ids.map(identifierFor).join(", ")}];`,
    "",
  ].join("\n");
}

/** Formats with the project's Prettier config, so the committed file never churns. */
export async function formatGenerated(source: string, root: string): Promise<string> {
  const filepath = join(root, GENERATED_FILE);
  const options = (await resolveConfig(filepath)) ?? {};
  return format(source, { ...options, filepath });
}

function isManifest(value: unknown): value is ModuleManifest {
  return typeof value === "object" && value !== null && "id" in value && "routePrefix" in value;
}

/** Imports each module's manifest (its default export). */
export async function loadManifests(
  root: string,
  ids: readonly string[],
): Promise<{ manifests: ModuleManifest[]; errors: string[] }> {
  const manifests: ModuleManifest[] = [];
  const errors: string[] = [];
  for (const id of ids) {
    if (!MODULE_ID.test(id)) {
      errors.push(`Module folder 'src/modules/${id}' isn't a kebab-case module id.`);
      continue;
    }
    const url = pathToFileURL(join(root, "src", "modules", id, "manifest.ts")).href;
    let loaded: unknown;
    try {
      loaded = await import(url);
    } catch (error) {
      errors.push(
        `src/modules/${id}/manifest.ts failed to load: ${error instanceof Error ? error.message : String(error)}`,
      );
      continue;
    }
    const manifest =
      typeof loaded === "object" && loaded !== null && "default" in loaded
        ? loaded.default
        : undefined;
    if (!isManifest(manifest)) {
      errors.push(`src/modules/${id}/manifest.ts must default-export defineModule({ ... }).`);
    } else if (manifest.id !== id) {
      errors.push(
        `src/modules/${id}/manifest.ts declares id '${manifest.id}'; it must match its folder '${id}'.`,
      );
    } else {
      manifests.push(manifest);
    }
  }
  return { manifests, errors };
}

/** lucide-react's canonical icon names (the keys of its `icons` export). */
export function lucideIconNames(): Set<string> {
  const indexFile = createRequire(import.meta.url).resolve("lucide-react/dist/esm/icons/index.mjs");
  const source = readFileSync(indexFile, "utf8");
  return new Set(
    [...source.matchAll(/export \{ default as (\w+) \}/g)].map((match) => match[1] ?? ""),
  );
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  // Manifests may import services that read the environment; codegen itself needs none.
  process.env.SKIP_ENV_VALIDATION ??= "1";
  const root = process.cwd();

  const ids = await discoverModuleIds(root);
  const { manifests, errors: loadErrors } = await loadManifests(root, ids);
  const errors = [
    ...loadErrors,
    ...validateManifests([coreManifest, ...manifests], { knownIcons: lucideIconNames() }),
  ];
  if (errors.length > 0) {
    console.error(`error registry: ${String(errors.length)} problem(s) in the module manifests:`);
    for (const error of errors) console.error(`  - ${error}`);
    process.exit(1);
  }

  const content = await formatGenerated(renderGenerated(ids), root);
  const target = join(root, GENERATED_FILE);
  const current = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (current === content) return;
  if (check) {
    console.error(`error ${GENERATED_FILE} is stale. Run pnpm registry:gen and commit the result.`);
    process.exit(1);
  }
  writeFileSync(target, content);
  console.warn(
    `ok    wrote ${GENERATED_FILE} (${String(ids.length)} module(s): ${ids.join(", ") || "none"})`,
  );
}

const invokedDirectly =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) await main();
