// Generated by `pnpm registry:gen` (src/platform/registry/codegen.ts). Don't edit it by hand.
// Every module manifest, imported statically and sorted by module id. Committed; CI fails
// when it's stale.

import type { ModuleManifest } from "@/contracts/module-manifest";

import acquisitionManifest from "@/modules/acquisition/manifest";

export const moduleManifests: readonly ModuleManifest[] = [acquisitionManifest];
