# src/modules/__MODULE_ID__/

**__MODULE_NAME__.** A FUTUREUNI platform module, generated by `pnpm create-module`. Its spec is
`docs/specs/module-__MODULE_ID__.md`.

| Path | What goes there |
|---|---|
| `manifest.ts` | Navigation, permissions, jobs, schedules, settings, widgets and commands (`docs/contracts/module-manifest.md`). Run `pnpm registry:gen` after changing it. |
| `core/` | Domain logic and services; database access only in `*.repo.ts` files |
| `ui/` | The module's components (built from `src/components/`) |
| `jobs.ts` | Background jobs, declared with `defineJob` |
| `seed.ts` | The idempotent development seed |

Rules: modules never import each other (lint-enforced); they share data through `@/platform/directory`,
`@/contracts` and domain events. The module's pages live in `src/app/(platform)__ROUTE_PREFIX__/`.
